### ISSUE TITLE
Please add an example

### ISSUE THREAD

**Issue by bjorn** [MasterOfRespawn/windows_exe_info#1]
This crate sounds really interesting since it seems like it could provide a very straight-forward way of adding an icon and some version information to a Windows build. However, the documentation is unfortunately very sparse, and I could not find any example.

Also, if I understand correctly, the `VersionInfo` struct has no defaults, though it seems to me that several of the fields could be taken from the `Cargo.toml` file, like version, product name and author. Is that something that could be added?

**Comment by MasterOfRespawn** [comment]
I just realized I did not add any examples. That was something I thought I did.

Reading fields for `VersionInfo` from `Cargo.toml` is a great idea I have not thought of, but I think this could be easily added.

**Comment by bjorn** [comment]
@MasterOfRespawn That's great, I see you've already worked on adding a default `VersionInfo`, thanks!

And in the meantime I had managed to find out how to add the icon at least: https://github.com/bjorn/raccoin/commit/cc58876ee2b7a4c88b656330b6e7a1e96d735a85 :-)

**Comment by MasterOfRespawn** [comment]
@bjorn I am happy to hear my crate is in use :)
I also have just finished testing the implementation of the default and added some examples.
Version 0.4 should now be published on crates.io if nothing went wrong. I hope it works in your project as well.

**Comment by bjorn** [comment]
@MasterOfRespawn That's great, I'll be trying it out soon!

One thing I noticed in your examples, is that they do not include the directives needed to make this Windows-only. But I think the majority of users of your crate will likely need to exclude this from their non-Windows builds, so I think it would be helpful to show users how to do that both in the `Cargo.toml` and the `build.rs` (you can see how I did it in my above patch).

Unless you can actually make it so that the crate will just do nothing on non-Windows systems. That would simplify its use and could be be preferable?

**Comment by bjorn** [comment]
I've updated to 0.4 (https://github.com/bjorn/raccoin/commit/cfd7fdc32713a9db8cdcc2810d985b562b9375cb), and it works! :-)

![image](https://github.com/MasterOfRespawn/windows_exe_info/assets/531764/571ea6c7-a233-447a-bfba-3cfe70ab0528)

**Comment by bjorn** [comment]
@MasterOfRespawn I've noticed you added the Windows check in d86f979eabb69e457b8532fff906bb0153b9b7d8. But why did you choose to do this as a feature and checking an environment variable? Is there a reason that `#[cfg(target_family = "windows")]` wouldn't do the trick?

**Comment by MasterOfRespawn** [comment]
@bjorn I just added it as a feature because I did not know if the environment variables are always correctly set or if there are any weird cross compilation issues. 
Using `#[cfg(target_famili = "windows")]` is sadly not possible as the cfg directive evaluates for to the build script and not the build target, so if it was used on windows to build for linux it would try to link the windows info and fail, however building for windows on linux would not link even try to link.
